CREATE DATABASE Tarragon;
use Tarragon;

CREATE TABLE IF NOT EXISTS Users(
    id INT(6) UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    email VARCHAR(50) NOT NULL,
    password VARCHAR(50) NOT NULL,
    UNIQUE (email)
);
CREATE TABLE IF NOT EXISTS Data(
    id INT(6) UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    user INT(6) NOT NULL,
    lic VARCHAR(20) NOT NULL,
    npi VARCHAR(20) NOT NULL,
    exp VARCHAR(30) NOT NULL,
    zip VARCHAR(20) NOT NULL,
    user_email VARCHAR(50) NOT NULL
);
